logging:
  level:
    org.springframework.web.HttpLogging: TRACE
    reactor.netty.http.server: DEBUG
    reactor.netty.http.client: DEBUG


spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
              allowedOrigins: "*"
              allowedHeaders: "*"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
                - PATCH
      routes:
        - id: forms_meta_route
          uri: ${FORMS_SERVICE_URI}
          predicates:
            - Path=/v1/meta/**
          filters:
            - RewritePath=/v1/meta/(?<PVARS>/?.*), /v1/meta/$\{PVARS}

        - id: forms_queries_route
          uri: ${FORMS_SERVICE_URI}
          predicates:
            - Path=/v1/queries/**
          filters:
            - RewritePath=/v1/queries/(?<PVARS>/?.*), /v1/queries/$\{PVARS}

        - id: forms_commands_route
          uri: ${FORMS_SERVICE_URI}
          predicates:
            - Path=/v1/commands/**
          filters:
            - RewritePath=/v1/commands/(?<PVARS>/?.*), /v1/commands/$\{PVARS}