logging:
  level:
    org.springframework.web.HttpLogging: TRACE
    reactor.netty.http.server: DEBUG
    reactor.netty.http.client: DEBUG

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
      routes:
        - id: forms_meta_route
          uri: ${FORMS_SERVICE_URI}
          predicates:
            - Path=/v1/meta/**
          filters:
            - RewritePath=/v1/meta/(?<PVARS>/?.*), /v1/meta/$\{PVARS}

        - id: forms_queries_route
          uri: ${FORMS_SERVICE_URI}
          predicates:
            - Path=/v1/queries/**
          filters:
            - RewritePath=/v1/queries/(?<PVARS>/?.*), /v1/queries/$\{PVARS}

        - id: forms_commands_route
          uri: ${FORMS_SERVICE_URI}
          predicates:
            - Path=/v1/commands/**
          filters:
            - RewritePath=/v1/commands/(?<PVARS>/?.*), /v1/commands/$\{PVARS}

        - id: data_service_queries_route
          uri: ${DATA_SERVICE_URI}
          predicates:
            - Path=/v1/data/queries
          filters:
            - RewritePath=/v1/data/queries, /v1/queries

        - id: data_service_commands_route
          uri: ${DATA_SERVICE_URI}
          predicates:
            - Path=/v1/data/commands
          filters:
            - RewritePath=/v1/data/commands, /v1/commands

        - id: data_service_meta_route
          uri: ${DATA_SERVICE_URI}
          predicates:
            - Path=/v1/data/meta/**
          filters:
            - RewritePath=/v1/data/meta/(?<PVARS>/?.*), /v1/meta/$\{PVARS}