logging:
  level:
    org.springframework.web.HttpLogging: TRACE
    reactor.netty.http.server: DEBUG
    reactor.netty.http.client: DEBUG

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "https://qa.bp2.cloud"
              - "https://bp2.cloud"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
      routes:
        # FORMS SERVICE ROUTES
        - id: forms_meta_route
          uri: ${FORMS_SERVICE_URI}
          predicates:
            - Path=/v1/meta/**
          filters:
            - RewritePath=/v1/meta/(?<PVARS>/?.*), /v1/meta/$\{PVARS}

        - id: forms_queries_route
          uri: ${FORMS_SERVICE_URI}
          predicates:
            - Path=/v1/queries/**
          filters:
            - RewritePath=/v1/queries/(?<PVARS>/?.*), /v1/queries/$\{PVARS}

        - id: forms_commands_route
          uri: ${FORMS_SERVICE_URI}
          predicates:
            - Path=/v1/commands/**
          filters:
            - RewritePath=/v1/commands/(?<PVARS>/?.*), /v1/commands/$\{PVARS}

        # DATA SERVICE ROUTES
        - id: data_service_queries_route
          uri: ${DATA_SERVICE_URI}
          predicates:
            - Path=/v1/data/queries
          filters:
            - RewritePath=/v1/data/queries, /v1/queries

        - id: data_service_commands_route
          uri: ${DATA_SERVICE_URI}
          predicates:
            - Path=/v1/data/commands
          filters:
            - RewritePath=/v1/data/commands, /v1/commands
        - id: data_service_commands_all_route
          uri: ${DATA_SERVICE_URI}
          predicates:
            - Path=/v1/data/commands/all
          filters:
            - RewritePath=/v1/data/commands/all, /v1/commands/all

        - id: data_service_meta_route
          uri: ${DATA_SERVICE_URI}
          predicates:
            - Path=/v1/data/meta
          filters:
            - RewritePath=/v1/data/meta, /v1/meta
        - id: data_service_meta_model_route
          uri: ${DATA_SERVICE_URI}
          predicates:
            - Path=/v1/data/meta/**
          filters:
            - RewritePath=/v1/data/meta/(?<PVARS>/?.*), /v1/meta/$\{PVARS}

        # LISTS SERVICE ROUTES
        - id: lists_service_queries_route
          uri: ${LISTS_SERVICE_URI}
          predicates:
            - Path=/v1/lists/queries/**
          filters:
            - RewritePath=/v1/lists/queries/(?<PVARS>/?.*), /v1/queries/$\{PVARS}

        - id: lists_service_commands_route
          uri: ${LISTS_SERVICE_URI}
          predicates:
            - Path=/v1/lists/commands
          filters:
            - RewritePath=/v1/lists/commands, /v1/commands